# Generated by Django 5.1.7 on 2025-04-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_images/'),
        ),
    ]
