# Generated by Django 5.1.7 on 2025-04-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
