# Generated by Django 5.1.7 on 2025-04-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('amount_left', models.IntegerField(blank=True, null=True)),
                ('total_amount_paid', models.IntegerField(blank=True, null=True)),
                ('first_payment_date', models.DateField(auto_now=True)),
                ('last_payment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
