# Generated by Django 5.1.7 on 2025-05-07 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_properties', '0001_initial'),
        ('my_tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('amount', models.IntegerField(default=0, help_text='Amount in pesewas')),
                ('currency', models.CharField(default='GHS', max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('provider', models.CharField(choices=[('mtn', 'MTN'), ('vodafone', 'Vodafone'), ('airteltigo', 'AirtelTigo')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('channel', models.CharField(default='mobile_money', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='my_properties.property')),
                ('tenancy_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='my_tenancy.tenancy_agreement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_paid', models.IntegerField(default=0)),
                ('amount_left', models.IntegerField(default=0)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('tenancy_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_summary', to='my_tenancy.tenancy_agreement')),
            ],
        ),
    ]
