# Generated by Django 5.1.7 on 2025-04-07 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('amount_left', models.IntegerField(blank=True, null=True)),
                ('total_amount_paid', models.IntegerField(blank=True, null=True)),
                ('first_payment_date', models.DateField(auto_now=True)),
                ('last_payment_date', models.DateField(auto_now_add=True)),
                ('tenancy_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='my_tenancy.tenancy_agreement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
