# Generated by Django 5.1.7 on 2025-04-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_tenant_id_image'),
        ('my_payments', '0001_initial'),
        ('my_tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tenancy_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='my_tenancy.tenancy_agreement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.tenant'),
        ),
    ]
