# Generated by Django 5.1.7 on 2025-05-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_payments', '0001_initial'),
        ('my_properties', '0002_unit_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='property',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenancy_agreement',
        ),
        migrations.AddField(
            model_name='payment',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='my_properties.unit'),
            preserve_default=False,
        ),
    ]
