# Generated by Django 5.1.7 on 2025-04-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='room_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
