# Generated by Django 5.1.7 on 2025-04-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='properties_images/'),
        ),
    ]
