# Generated by Django 5.1.7 on 2025-05-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='availability',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
