# Generated by Django 5.1.7 on 2025-04-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0002_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='availability',
            field=models.BooleanField(),
        ),
    ]
