# Generated by Django 5.1.7 on 2025-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0002_unit_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
