# Generated by Django 5.1.7 on 2025-04-11 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0003_alter_property_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='cost_of_rent',
            new_name='no_of_floors',
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
