# Generated by Django 5.1.7 on 2025-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0003_alter_unit_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(default='no', max_length=500),
        ),
    ]
