# Generated by Django 5.1.7 on 2025-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0004_property_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
