# Generated by Django 5.1.7 on 2025-05-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0005_alter_property_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='image_url',
            field=models.URLField(default='will upload later', max_length=500),
        ),
    ]
