# Generated by Django 5.1.7 on 2025-05-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0006_unit_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
