# Generated by Django 5.1.7 on 2025-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_properties', '0007_alter_unit_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('1bed', '1 Bedroom')], default='Studio', max_length=50),
        ),
    ]
